"""Add extra fields to User model

Revision ID: 4bad1256e0da
Revises: ccfa9d4ce430
Create Date: 2025-06-10 16:26:00.828459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bad1256e0da'
down_revision = 'ccfa9d4ce430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
